export const contactList = [
  { id: 1, name: 'Agustín Perez', initials: 'AP', bank: 'Banco Nación' },
  { id: 2, name: 'Alicia Strada', initials: 'AS', bank: 'Brubank' },
  { id: 3, name: 'Fernando Fernandez', initials: 'FF', bank: 'Banco Galicia' },
  { id: 4, name: 'Franco Strada', initials: 'FS', bank: 'Banco Macro' },
  { id: 5, name: 'Gonzalo Martinez', initials: 'GM', bank: 'Banco Santander Río' },
  { id: 6, name: 'Hernan Garcia', initials: 'HG', bank: 'Ualá' },
  { id: 7, name: 'Leandro Sol', initials: 'LS', bank: 'Wilobank' },
  { id: 8, name: 'Lucas Torres', initials: 'LT', bank: 'Banco Patagonia' },
  { id: 9, name: 'Manuel Carlos', initials: 'MC', bank: 'Banco Itaú' },
  { id: 10, name: 'Martín Strada', initials: 'MS', bank: 'Banco Hipotecario' },
  { id: 11, name: 'Nelson Cuevas', initials: 'NC', bank: 'Banco Credicoop' },
  { id: 12, name: 'Pedro Gomez', initials: 'PG', bank: 'Banco BBVA Argentina' },
  { id: 13, name: 'Proveedor A', initials: 'PA', bank: 'Rebanking' },
  { id: 14, name: 'Proveedor B', initials: 'PB', bank: 'Prex' },
  { id: 15, name: 'Proveedor C', initials: 'PC', bank: 'MODO' },
  { id: 16, name: 'Proveedor E', initials: 'PE', bank: 'Banco Nación' },
  { id: 17, name: 'Renzo Calvo', initials: 'RC', bank: 'Brubank' },
  { id: 18, name: 'Roman Strada', initials: 'RS', bank: 'Banco Galicia' },
  { id: 19, name: 'María Fernanda Perez', initials: 'MFP', bank: 'Banco Macro' },
  { id: 20, name: 'Fernando José Fernandez', initials: 'FJF', bank: 'Banco Santander Río' },
  { id: 21, name: 'Franco José Strada', initials: 'FJS', bank: 'Ualá' },
  { id: 22, name: 'Gonzalo Andrés Martinez', initials: 'GAM', bank: 'Wilobank' },
  { id: 23, name: 'Hernan Javier Garcia', initials: 'HJG', bank: 'Banco Patagonia' },
  { id: 24, name: 'Lucas Andres Torres', initials: 'LAT', bank: 'Banco Itaú' },
  { id: 25, name: 'Manuel David Carlos', initials: 'MDC', bank: 'Banco Hipotecario' },
  { id: 26, name: 'Martín Alberto Strada', initials: 'MAS', bank: 'Banco Credicoop' },
  { id: 27, name: 'Nelson Santiago Cuevas', initials: 'NSC', bank: 'Banco BBVA Argentina' },
  { id: 28, name: 'Pedro Alberto Gomez', initials: 'PAG', bank: 'Rebanking' },
  { id: 29, name: 'Alicia Fernanda Strada', initials: 'AFS', bank: 'Prex' },
  { id: 30, name: 'Renzo Javier Calvo', initials: 'RJC', bank: 'MODO' },
  { id: 31, name: 'Roman José Strada', initials: 'RJS', bank: 'Banco Nación' },
  { id: 32, name: 'Ricardo Gomez', initials: 'RG', bank: 'Brubank' },
  { id: 33, name: 'Roberto Cuevas', initials: 'RC', bank: 'Banco Galicia' },
  { id: 34, name: 'Gonzalo José Martinez', initials: 'GJM', bank: 'Banco Macro' },
  { id: 35, name: 'Fernando Calvo', initials: 'FC', bank: 'Banco Santander Río' },
  { id: 36, name: 'Fabián Strada', initials: 'FS', bank: 'Ualá' },
  { id: 37, name: 'Marcelo José Torres', initials: 'MJT', bank: 'Wilobank' },
  { id: 38, name: 'Marcelo Torres', initials: 'MT', bank: 'Banco Patagonia' },
  { id: 39, name: 'Mariana Perez', initials: 'MP', bank: 'Banco Itaú' },
  { id: 40, name: 'Marta Sol', initials: 'MS', bank: 'Banco Hipotecario' },
  { id: 41, name: 'Lucia Strada', initials: 'LS', bank: 'Banco Credicoop' },
  { id: 42, name: 'Luciano Torres', initials: 'LT', bank: 'Banco BBVA Argentina' },
  { id: 43, name: 'Pedro Hernandez', initials: 'PH', bank: 'Rebanking' },
  { id: 44, name: 'Hernan Sol', initials: 'HS', bank: 'Prex' },
  { id: 45, name: 'Hernan Martinez', initials: 'HM', bank: 'MODO' },
  { id: 46, name: 'Hernan Perez', initials: 'HP', bank: 'Banco Nación' },
  { id: 47, name: 'Fernando Martinez', initials: 'FM', bank: 'Brubank' },
  { id: 48, name: 'Federico Sol', initials: 'FS', bank: 'Banco Galicia' },
  { id: 49, name: 'Agustín Perez', initials: 'AP', bank: 'Banco Macro' },
  { id: 50, name: 'Alicia Strada', initials: 'AS', bank: 'Banco Santander Río' },
];
