export const TERMS_AND_CONDITIONS_INV_SALDOS = `
Términos y Condiciones Apertura Cuenta Comitente e Inversión de Saldos
Estos términos y condiciones (en adelante, los “Términos y Condiciones” o “T&C”) constituyen un contrato entre usted (en adelante, el “Usuario” o, en plural, “Usuarios”) y la Empresa XXXX (COMPLETAR CUIT) sociedad inscripta en la Inspección General de Justicia de la Capital Federal con fecha XX de XX de XXXX bajo el número XX del Libro XX Tomo X de Sociedades Anónimas con domicilio en (COMPLETAR DOMICILIO), de la Ciudad Autónoma de Buenos Aires, República Argentina (en adelante, la “Empresa” y, junto con el Usuario, las “Partes” o en forma individual como la “Parte”), con el objeto de que el Usuario pueda instruir para invertir sus saldos disponibles en su cuenta Virtual (la “Cuenta Virtual”) – abierta en la Empresa - en cuotapartes del Fondo Común de Inversión Delta Pesos (las “Cuotapartes” y el “Fondo”, respectivamente), que es administrado por Delta Asset Management S.A., CUIT Nro 33-70917291-9, con domicilio en Maipú 1186 Piso 6°, Ciudad Autónoma de Buenos Aires (en adelante, “Delta”) en su carácter de sociedad gerente (en adelante, “Sociedad Gerente”) inscripta ante la Comisión Nacional de Valores (“CNV”) y cuya custodia de activos está a cargo de Banco de Valores S.A., CUIT N° 30-57612427-5, en su carácter de sociedad depositaria (en adelante, “Sociedad Depositaria” y/o “Banco de Valores”, indistintamente) inscripta ante la Comisión Nacional de Valores (CNV) (en adelante, el “Servicio”).
QUIEN NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE INSTRUIR A INVERTIR SUS SALDOS DISPONIBLES. El Usuario de la Empresa se obliga a leer cuidadosamente estos Términos y Condiciones, que incluyen expresamente cualquier página adicional o complementaria vinculada desde la Plataforma. Todo usuario deberá leer, entender y aceptar las condiciones establecidas en los Términos y Condiciones de forma previa a la instrucción de inversión. La registración en la Empresa y la instrucción de inversión será entendida como una aceptación plena y sin reservas a estos Términos y Condiciones.
Al aceptar los Términos y Condiciones, el Usuario podrá instruir a invertir sus saldos disponibles en su Cuenta Virtual (CVU) abierta en la EMPRESA, bajo una cuenta comitente de su titularidad, en cuotapartes del Fondo Común de Inversión denominado “Delta Pesos”, administrado por Delta, en su carácter de Sociedad Gerente, y cuya custodia de activos está a cargo del Banco de Valores, en su carácter de Sociedad Depositaria.
Al aceptar estos Términos y Condiciones, el Usuario acepta expresamente – y sin reservas -las condiciones previstas en el reglamento de gestión del Fondo (en adelante, “Reglamento de Gestión de Fondo”) el que se encuentra disponible en https://deltaam.com.ar/fondos_de_inversion/delta-pesos.
El Usuario acepta expresamente – y sin reservas - que la documentación e información relacionada con los Términos y Condiciones será publicada exclusivamente mediante soporte electrónico.
Los presentes Términos y Condiciones se componen además por los otros términos y condiciones de uso de la Plataforma publicados en la Plataforma y en el sitio web de la Empresa, y cuyo contenido el Usuario manifiesta haber leído y aceptado expresamente.
Los Términos y Condiciones entrarán en plena vigencia para cada Usuario a partir de su aceptación por el Usuario, y se mantendrán vigentes, incluyendo sus Actualizaciones, hasta que el Usuario no tenga el carácter de tal.

1. El Servicio.
1.1. Sólo podrán acceder al Servicio aquellas personas que cumplan los requisitos establecidos en estos Términos y Condiciones y los Términos y Condiciones Generales de Uso de la EMPRESA. A todo evento, no podrán registrarse ni acceder al Servicio los menores de edad, las personas que no tengan capacidad para contratar y/o aquellos Usuarios que hayan sido suspendidos y/o inhabilitados por la EMPRESA, en forma temporal o definitivamente.
1.2. Se deja constancia que la EMPRESA SE LIMITA A OFRECER SERVICIOS DE PAGO Y NO SE ENCUENTRA AUTORIZADA A OPERAR COMO ENTIDAD FINANCIERA POR EL BANCO CENTRAL DE LA REPÚBLICA ARGENTINA. LA EMPRESA NO PRESTA NINGÚN SERVICIO BANCARIO NI CAMBIARIO. LOS FONDOS DEPOSITADOS EN CUENTAS DE PAGO NO CONSTITUYEN DEPÓSITOS EN UNA ENTIDAD FINANCIERA, NI CUENTAN CON NINGUNA DE LAS GARANTÍAS QUE TALES DEPÓSITOS PUEDAN GOZAR DE ACUERDO CON LA LEGISLACIÓN Y REGLAMENTACIÓN APLICABLE EN MATERIA DE DEPÓSITOS DE ENTIDADES FINANCIERAS” (Comunicación “A” 6885 y sig. del BCRA).
1.3. El Usuario entiende y acepta que la información relevante vinculada con el Servicio a través del Fondo estará disponible en todo momento en https:// deltaam.com.ar/nuestros-fondos/. Allí se publicarán los honorarios y gastos actualizados imputables al Fondo. Salvo que allí se indique lo contrario, Delta cobrará un honorario de administración del XX % anual y Banco de Valores cobrará un honorario por la custodia de 0,10 % anual, ambos honorarios calculados sobre el patrimonio del Fondo y, en ambos casos más IVA de ser aplicable, que se devengarán diariamente y se percibirán de manera mensual. Asimismo, existen gastos ordinarios de gestión que serán deducibles del Fondo. No existen comisiones de suscripción ni de rescate. Delta no percibirá honorarios del Usuario por su actuación como colocador del Fondo.
1.4. El Servicio se presta a través de una modalidad de colocación de Cuotapartes del Fondo que cumple con lo dispuesto por las normas (N.T. 2013 y mod.) de la CNV y sus normas complementarias y modificatorias (las “Normas de la CNV”), y las actividades de Delta y Banco de Valores se encuentran comprendidas dentro de las autorizaciones otorgadas por la CNV.
1.5. Las inversiones en Cuotapartes del Fondo no constituyen depósitos en Banco de Valores, a los fines de la Ley de Entidades Financieras ni cuentan con ninguna de las garantías que tales depósitos a la vista o a plazo puedan gozar de acuerdo con la legislación y reglamentación aplicables en materia de depósitos en entidades financieras. Asimismo, Banco de Valores, se encuentra impedida por normas del Banco Central de la República Argentina (“BCRA”) de asumir, tácita o expresamente, compromiso alguno en cuanto al mantenimiento, en cualquier momento, del valor del capital invertido, al rendimiento, al valor de rescate de las Cuotapartes o al otorgamiento de liquidez a tal fin. Rendimientos pasados no garantizan rendimientos futuros. Las inversiones están sujetas a riesgos que pueden incluir la pérdida de capital.
1.6. La Empresa presta sus servicios de procesamiento de pagos y billetera digital acorde a las instrucciones que sean impartidas por el Usuario y por Delta conforme a los T&C, a los fines de permitir la suscripción y rescate de Cuotapartes.

2. Declaraciones. Responsabilidad.
2.1. Es condición esencial para el uso del Servicio el compromiso del Usuario de utilizarlo en forma lícita y de acuerdo con estos T&C y la normativa aplicable, y la aceptación de la obligación de proveer información que le sea solicitada en cumplimiento de la normativa aplicable. El Usuario será responsable por el uso ilícito y/o contrario a los Términos y Condiciones y/o reglamento del Fondo y/o la normativa aplicable.
2.2. Ni la Empresa, ni Delta ni Banco de Valores serán responsables de los daños o perjuicios que el Usuario pudiera sufrir derivados del acceso, uso y/o mala utilización de los contenidos del Servicio, siendo el Usuario el único y exclusivo responsable por ello.
2.3. Ni la Empresa, ni Delta ni Banco de Valores serán responsables si por cualquier causa fuera imposible acceder al Servicio, se desconectara el mismo, o por los accesos no exitosos a cualquiera de los vínculos incluidos en el Servicio.
2.4. Queda prohibida la copia, duplicación, redistribución, comercialización o cualquier otra actividad que se pueda realizar con los contenidos del Servicio por parte del Usuario.
2.5. Queda expresamente determinado que el Usuario deberá ajustarse íntegramente a la totalidad de los términos y condiciones que se establezcan en la Plataforma, incluyendo todo lo dispuesto en relación a los Términos y Condiciones de Uso de la Empresa disponibles en la Plataforma y en su sitio web en relación al procesamiento de pagos que la Empresa realice a fin de que el Usuario y/o representante legal suscriba y/o rescate Cuotapartes del Fondo.
2.6. Los Usuarios entienden y aceptan que, en caso de revestir el carácter de personas jurídicas, personas humanas responsables inscriptas o personas humanas monotributistas y decidan invertir sus saldos disponibles de la Cuenta Virtual en Cuotapartes del Fondo, deberán con carácter previo a la apertura de la cuenta comitente cumplir con el Censo Nacional Económico (CNE 2020-2021), de conformidad con lo dispuesto por el Resolución 180/2020 del Instituto Nacional de estadística y Censos (INDEC) y la Comunicación “B” 121100/2020 del BCRA. El presente requisito comenzará a regir de conformidad con el siguiente cronograma: (i) desde el 1° de abril de 2021 para las personas jurídicas; (ii) 1° de mayo de 2021 para las personas humanas responsables inscriptas; y (iii) 1° de julio de 2021 para las personas humanas monotributistas. Los Usuarios reconocen y aceptan que, ante requerimiento de Banco de Valores, deberán poner a disposición el certificado de cumplimiento censal correspondiente.
2.7. Delta y Banco de Valores (i) podrán solicitar a la Empresa en cualquier momento, los legajos de información y/o documentación del Usuario a fin de dar cumplimiento a obligaciones regulatorias de conocimiento del Usuario de conformidad con la normativa aplicable, para lo cual el Usuario presta su consentimiento a fin que la Empresa provea dicha información y/o documentación; (ii) informarán a la Empresa de manera inmediata en caso de recibir cualquier notificación o requerimiento que pudiera afectar las inversiones del Usuario, incluyendo embargos, reclamos y otras medidas adoptadas por una autoridad competente.
2.8. El Usuario utilizará para el ingreso a su Cuenta Virtual el correo electrónico y la clave personal que haya utilizado para registrarse en la Plataforma de acuerdo a todos los requisitos de acceso establecidos por la Empresa. La Empresa, Delta y Banco de Valores no son responsables por errores, omisiones, atrasos o inconvenientes en el procesamiento de las operaciones de suscripción y rescate de Cuotapartes generados por la transmisión incorrecta de datos o informaciones, o por una avería o falla en los servicios y sistemas de transmisión de datos, como tampoco serán responsables por falta de servicios de transmisión de datos y/o servicios de conexión a Internet. En consecuencia, la Empresa, Delta y Banco de Valores, sus directores, funcionarios, personal, y agentes no son responsables por las pérdidas acaecidas cuando sean causadas directa o indirectamente por estas causales. En su mérito, los Usuarios liberan a la Empresa de toda responsabilidad por ello y renuncian a todo reclamo en su contra.
2.9. El Usuario podrá: (i) realizar operaciones de suscripción y rescate de Cuotapartes, (ii) consultar su valuación, sus movimientos de cuenta en su Cuenta Virtual, y el detalle de operaciones diarias vigentes a la fecha de la consulta en el Servicio, y en el periodo que se estipule oportunamente, así como otros datos conforme se implementen a futuro.
2.10. La Empresa, la Sociedad Gerente y la Sociedad Depositaria, no asumen responsabilidad alguna por el cumplimiento de las obligaciones fiscales que pudieran resultar de la inversión de las Cuotapartes en el Fondo. En este sentido, todos los impuestos, tasas, contribuciones y demás obligaciones tributarias que se generen como consecuencia de la operatoria serán a cargo del Usuario.
2.11. La información suministrada, los resultados de las fases interactivas (“Test de inversor”, etc.) y/o cualquier elemento del Fondo no constituye en sí una recomendación de contratación de servicios o inversiones específicas, no se aseguran rendimientos futuros de ningún tipo, ni suplanta la toma de decisiones de inversión, con el debido y previo asesoramiento legal, fiscal y contable a cargo del Usuario. No se garantiza el carácter genuino o la veracidad de la información pública, ni se asume obligación alguna de actualizar cualquiera de los datos incorporados en el documento. Se encuentra prohibida la distribución o reproducción –total o parcial– de dicha información. En consecuencia, el Usuario asume los riesgos de este tipo de operatoria.
2.12. La responsabilidad por la administración y gestión del Fondo y la responsabilidad por la custodia de los activos que lo componen recaerá exclusivamente sobre Delta en su carácter de Sociedad Gerente inscripta ante la CNV y sobre Banco de Valores en su carácter de Sociedad Depositaria inscripta ante la CNV, respectivamente. La Empresa no tiene responsabilidad alguna por dicha administración, gestión y custodia de los fondos y activos de los Usuarios una vez tomada la decisión de suscribir Cuotapartes del Fondo de acuerdo con los T&C.

3. Mandatos irrevocables a la Empresa, Delta y Banco de Valores - Autorización.
3.1. El Usuario instruye a Delta, en su carácter de Sociedad Gerente, y a Banco de Valores, en su carácter de Sociedad Depositaria, a que éstos generen por su cuenta y orden las órdenes de suscripción y de rescate de Cuotapartes del Fondo. En consecuencia, el Usuario autoriza e instruye irrevocablemente en este acto a Delta y a Banco de Valores en forma indistinta para que, por su cuenta y orden, y conforme a las decisiones del Usuario, suscriba la documentación necesaria y realice los actos jurídicos y/o materiales necesarios o convenientes para la inversión de los saldos y/o suscripción y/o rescate de Cuotapartes del Fondo. El Usuario entiende y acepta que a tal fin se utilizará la modalidad de Agente de Colocación y Distribución Integral (ACDI), rol que asumirá Delta en todo conforme con las normas aplicables. El Usuario entiende y acepta que esta modalidad incluye la apertura de cuentas comitentes de su titularidad en Caja de Valores S.A. (en su carácter de Agente Depositario Central de Valores Negociables o ADCVN, autorizado por la CNV) para la custodia de las Cuotapartes que suscriba, y el registro de las Cuotapartes en el sistema de Banco de Valores; y el Usuario instruye a Delta para que reciba de manera directa las comunicaciones correspondientes de Banco de Valores. El Usuario entiende y acepta que Delta, Banco de Valores, y Caja de Valores S.A., en el marco de lo que autoricen las Normas, podrán utilizar otros sistemas en lugar del mencionado.
3.2. El Usuario autoriza e instruye irrevocablemente en este acto a la Empresa para que, por su cuenta y orden, y conforme a las decisiones del Usuario, realice el procesamiento de los pagos y cobros vinculados con las instrucciones de suscripción y rescates de Cuotapartes del Fondo. Sin limitación de lo anterior, ello implica debitar, acreditar, retener y/o realizar cualquier acto necesario con los fondos disponibles en la Cuenta Virtual del Usuario.
3.3. El Usuario entiende que, adoptada su decisión e impartida su instrucción de invertir en el Fondo, todo dinero que ingrese al CVU del Usuario será invertido automáticamente en el Fondo, de conformidad con la decisión del Usuario, y sin perjuicio de la facultad de modificar dicha decisión en el futuro. Los rendimientos de dicha inversión serán reflejados en la Cuenta Virtual del Usuario.
3.4. Cada vez que el Usuario decida utilizar y/o rescatar –total o parcialmente- las Cuotapartes con el fin de (i) cancelar pagos por la compra de bienes, productos o servicios; (ii) realizar transferencias a cuentas bancarias y/o cuentas de pago , (iii) retirar fondos en efectivo a través de redes de cobranzas extrabancarias habilitadas, y/o (iv) rescatar las Cuotapartes con el fin de mantener el dinero disponible en su Cuenta Virtual, ello implicará una instrucción de rescate emitida por el Usuario, y por tanto Delta y Banco de Valores procederán a rescatar las Cuotapartes por cuenta y orden del Usuario, aceptando el Usuario que a los efectos de permitir la disponibilidad inmediata de fondos, los rescates de Cuotapartes pueden implementarse a través de mecanismos de compensación.
3.5. Sin perjuicio de los puntos detallados en los puntos i) a iv), los eventos detallados a continuación, implicarán asimismo una instrucción de rescate de Cuotapartes del Fondo emitida por el Usuario y, por lo tanto, Delta y/o Banco de Valores estarán facultados a rescatar las Cuotapartes del Usuario, otorgando éste un mandato expreso a tal fin y autorizando la actuación por su cuenta y orden: (i) Orden judicial que indicara o requiriera para su cumplimiento el rescate de las Cuotapartes; (ii) Si el Usuario tuviera saldos deudores a cubrir en su Cuenta Virtual por servicios ofrecidos por la Empresa, Delta y/o Banco de Valores; (iii) Si el Usuario tuviera responsabilidad frente a la Empresa por contracargos generados en su Cuenta Virtual de acuerdo a los Términos y Condiciones de Uso; (iv) Si los datos de la Cuenta Virtual del Usuario no coincidieran con los datos registrados en Delta y Banco de Valores o cualquier otra irregularidad vinculada a los datos personales del Usuario; (v) Otras causales que Delta y Banco de Valores tengan a consideración por las cuales la cuenta comitente de un Usuario deba ser inhabilitada y/o cerrada.
3.6. Los mandatos indicados son otorgados por el plazo de UN (1) año, renovables automáticamente, salvo decisión en contrario del Usuario, comunicada por escrito.
3.7. La Empresa, Delta y Banco de Valores se encuentran facultados de manera irrestricta para trabar embargos, con el consecuente bloqueo de Cuotapartes y/o aplicar cualquier otra medida cautelar que les fuera ordenada por autoridad competente, incluyendo sin limitación, la inhabilitación de la cuenta comitente en caso de quiebra; quedando, durante el plazo de vigencia de la cautelar, inhabilitada la opción de rescate de los valores prendados. Asimismo, la Empresa, Delta y Banco de Valores, ante la traba de un embargo (o cualquier otra medida cautelar), podrán imposibilitar al Usuario la realización de futuras inversiones. El Usuario reconoce y acepta que tanto el Banco de Valores como entidad financiera y la Empresa en su carácter de proveedor de servicios de pago, deben cumplir con las comunicaciones difundidas por el BCRA relativos a la traba de embargos y otras medidas cautelares.

4. Política de Privacidad.
4.1. La Empresa se preocupa por mantener la confidencialidad de los Datos Personales y proteger los mismos de los accesos no autorizados. El Usuario podrá conocer la forma en la que la Empresa protege, recaba y trata los Datos Personales accediendo a su Política de Privacidad de Datos a través de la Plataforma o su sitio web.
4.2. Las Políticas de Privacidad de la Empresa, Delta y Banco de Valores, respectivamente, cumplen las exigencias de la Ley 25.326, su decreto reglamentario y normas complementarias (“Ley de Protección de Datos Personales”).
4.3. Sin perjuicio de lo dispuesto en las Políticas de Privacidad de la Empresa, el Usuario entiende y acepta que la totalidad de la información que suministre a la Empresa, Delta y/o Banco de Valores es necesaria para la ejecución de los T&C, y presta declaración jurada de su veracidad, exactitud, integridad, vigencia y autenticidad, y autoriza a que la misma sea compartida entre la Empresa, Delta y/o Banco de Valores, y prestadores de servicios, especialmente en el marco de lo previsto por la Ley 25.246 y su normativa reglamentaria. La Empresa, Delta y/o Banco de Valores se reservan el derecho de solicitar al Usuario información adicional relacionada con la obtención y tenencia de activos del Usuario, incluyendo -entre otra información- la justificación de origen lícito de sus fondos, consintiendo expresamente el Usuario tal facultad.
4.4. El Usuario entiende y acepta sin reservas que su información está sujeta a análisis y deberes de reporte o información, de conformidad con la regulación de la Comisión Nacional de Valores, Banco Central de la República Argentina, Unidad de Información Financiera u otros entes, incluyendo, enunciativamente, la regulación FATCA –Foreign Account Tax Compliance Act–, y las de implementación del régimen de intercambio de información OCDE –Organización para la Cooperación y el Desarrollo Económico–.

5. Impuestos.
5.1. La Empresa, Delta y Banco de Valores no asumen responsabilidad alguna por el cumplimiento de las obligaciones fiscales de los Usuarios que pudieran resultar de la inversión en Cuotapartes del Fondo, según lo previsto en los presentes T&C. En este sentido, todos los impuestos, tasas, contribuciones y demás obligaciones tributarias (nacionales, provinciales y municipales) que se generen como consecuencia de la inversión en Cuotapartes del Fondo, estarán a cargo única y exclusivamente del Usuario.

6. Disposiciones Adicionales. Autorización.
6.2. El Usuario autoriza e instruye expresamente a la Empresa a recibir de manera directa todas las comunicaciones emitidas por Caja De Valores S.A. en el marco del Servicio solicitado.
No obstante, el Usuario podrá revocar la autorización e instrucción aquí otorgada, comunicando dicha decisión, por escrito, a la Empresa a través de los canales de contacto habilitados.
6.3. La Empresa, no se responsabiliza por los posibles daños y perjuicios, de cualquier tipo que fueren, que pudieren sufrir los Usuarios, en ocasión y con motivo de la autorización e instrucción otorgada a la Empresa en el punto 6.2. de los presentes Términos y Condiciones.

7. Modificaciones y/o Actualizaciones a los Términos y Condiciones.
7.1. La Empresa, Delta y/o Banco de Valores se reservan el derecho de realizar modificaciones y/o actualizaciones a los T&C y reglamentos del Fondo (las “Actualizaciones”), a fin de adaptarlos a nuevas disposiciones operativas, normas y reglamentaciones aplicables sin limitación alguna, por una obligación legal o contractual que así lo determine. Todas las Actualizaciones entraran a regir al momento de su publicación.
7.2. El Usuario entiende y acepta que el uso del Servicio después de las Actualizaciones constituye la aceptación de tales Actualizaciones, salvo comunicación en forma expresa del Usuario a la Empresa , Delta y/o Banco de Valores, lo cual implicará que el Usuario podrá ser dado de baja del Servicio. La Empresa, Delta y/o Banco de Valores se encuentran facultados, sin necesidad de aprobación del Usuario, a modificar, enmendar, suspender, transitoria o definitivamente, o dar de baja el Servicio.

8.	Servicios de Terceros.
A los fines de prestar nuestros servicios podremos utilizar o recurrir a servicios de terceros proveedores. En su mérito, toda autorización, mandato, renuncia, indemnidad, y en general, cualquier otra disposición prevista en estos Términos y Condiciones para la prestación de los Servicios debe entenderse realizada por el Usuario a favor de la Empresa y/o sus proveedores de servicios.

9.	Términos en mayúsculas.
Los términos en mayúscula que no estén definidos en estos Términos y Condiciones de tendrán el significado asignado a los mismos en los Términos y Condiciones de Uso de la Empresa.
Para todo lo aquí no previsto será de aplicación lo dispuesto en los Términos y Condiciones de Uso de la Empresa.

10.	Canales de Atención.
La Empresa brinda al Usuario distintos canales de atención para que éste pueda despejar sus dudas o realizar consultas relacionadas con la Inversión. El Usuario podrá obtener en:
Domicilio: [________]
Teléfono: [________]
E-mail: [________]

11. Domicilio. Ley aplicable. Competencia.
11.1. Estos Términos y Condiciones se rigen por las leyes de la República Argentina.
12.2. Ante cualquier controversia o divergencia relacionada con la interpretación, validez, celebración o cumplimiento de los mismas, las Partes declaran que se someten a la jurisdicción de los Tribunales que resulten competentes conforme la legislación aplicable.
13.3. Las controversias vinculadas al Fondo se resolverán conforme lo previsto en el Reglamento de Gestión del Fondo aprobado por la CNV.
`;
