export const TERMS_AND_CONDITIONS_CONTENT = `

El uso de la Plataforma ofrecida por la Empresa se rige por los términos y condiciones generales que se describirán a continuación (los "Términos y Condiciones") y los respectivos Anexos, Políticas de Privacidad y demás documentos relacionados.


Cualquier persona que desee acceder y/o usar la Plataforma ofrecida por la Empresa, en cualquiera de sus modalidades y servicios, deberá hacerlo sujetándose a estos Términos y Condiciones, junto con todas las demás políticas, principios y Anexos que rigen los servicios ofrecidos. QUIEN NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES, SUS ANEXOS Y POLÍTICAS DE PRIVACIDAD, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR LA PLATAFORMA Y/O LOS SERVICIOS OFRECIDOS POR LA EMPRESA. Todo usuario deberá leer, entender y aceptar las condiciones establecidas en los Términos y Condiciones de forma previa o simultánea a su registración. Asimismo, podrá optar de forma expresa por recibir los presentes y toda otra información por medios digitales. La registración en la Empresa y la utilización de los productos y servicios ofrecidos será entendida como una aceptación plena y sin reservas a estos Términos y Condiciones, Políticas de Privacidad y demás Anexos que rigen el uso de la Plataforma.


1. Actualización.
Es posible que periódicamente actualicemos estos Términos y Condiciones y sus Anexos, las Políticas de Privacidad, los productos y servicios ofrecidos y/o la Plataforma, proporcionando correcciones de errores, nuevas funciones o modificaciones (las "Actualizaciones"). Todas estas Actualizaciones entrarán a regir a partir del momento de su publicación y/o puesta en funcionamiento. También podemos pedirte que instales Actualizaciones y deberás hacerlo con prontitud. La falta de instalación de estas Actualizaciones puede exponerte a riesgos de seguridad y/o limitar nuestra capacidad de proporcionar los servicios. Las Actualizaciones estarán sujetas a estos Términos y Condiciones junto con los términos y condiciones adicionales que se pueden proporcionar con dicha Actualización. El uso de la Plataforma luego de la publicación de los nuevos Términos y Condiciones, Políticas de Privacidad o Anexos constituirá la aceptación de todos los términos adicionales y/o actualizados por el Usuario. La Empresa no se responsabiliza por los daños ocasionados como consecuencia de fallas de seguridad originadas por la falta de instalación de las Actualizaciones requeridas.


2. Definiciones.
A todos los efectos de estos Términos y Condiciones se entenderá por:


- CBU: es la Clave Bancaria Uniforme que identifica una cuenta bancaria.
- Cuenta Bancaria: es la cuenta bancaria a la vista de titularidad del Usuario en alguna entidad financiera de la República Argentina conforme Ley Nº 21.526 que puede estar vinculada a la Cuenta Virtual de cada uno de ellos.
- Cuenta(s) recaudadora(s): es la/s cuenta/s bancaria/s a la vista en la cual se mantienen los fondos que los Usuarios poseen en sus Cuentas Virtuales, salvo que éstos hayan instruido expresamente a la Empresa a invertir sus saldos en un Fondo Común de Inversión.
- Cuenta Virtual: es la cuenta que los Usuarios poseen en la Empresa y a través de la cual podrán acceder a los diferentes productos y servicios junto con cualquier otra funcionalidad que en un futuro se ofrezca en la Plataforma sujeto a los términos y condiciones que se establezcan para cada funcionalidad.
- CVU: es la Clave Virtual Uniforme que posee y/o está asociada a cada de las Cuentas Virtuales.
- Plataforma: es la plataforma online a través de la cual la Empresa ofrece productos y servicios al Usuario principalmente financieros.
- La Empresa: es la firma Wibond SAS., CUIT N° 30716108720, con domicilio en calle Obispo Oro 324, Córdoba, República Argentina.
- Usuario(s): Es toda persona humana o jurídica debidamente registrada en la Plataforma que cuente con la capacidad exigida y que utilice alguno de los servicios ofrecidos por la Empresa en cualquiera de las modalidades/carácter disponible en cada caso.


3. ¿Qué Servicios encontrarás en la Plataforma?
A través de la Plataforma, la Empresa ofrece servicios y/o productos financieros que conforman un ecosistema integral, principalmente vinculado a cobros y pagos digitales. Estos servicios incluyen, entre otros el ofrecimiento de Cuentas Virtuales, que permiten a título enunciativo, realizar y recibir transferencias desde y hacia otras cuentas bancarias o de pago, así como realizar el ingreso o retiro de fondos a través de canales habilitados, realizar pagos utilizando el dinero disponible en la CVU, acceder a los movimientos transaccionales y financieros, invertir los fondos disponibles en un fondo común de inversión y/o acceder a tarjetas prepagas.


4. ¿Qué necesitas para ser Usuario de la Plataforma?
Para ser Usuario de la Plataforma deberás tener la capacidad legal necesaria para ello, aceptar los Términos y Condiciones y estar registrado en la Plataforma.


4.1. Capacidad. Sólo podrán acceder y usar la Plataforma aquellas personas tanto humanas como jurídicas que tengan capacidad legal para contratar y cumplan con los requisitos de registración de la misma. No podrán registrarse ni utilizar los servicios menores de edad, personas que no tengan capacidad legal para contratar o aquellos Usuarios que hayan sido suspendidos o inhabilitados por la Empresa, temporal o definitivamente. En caso de que el Usuario sea una persona jurídica, la persona humana que realice la registración en su nombre deberá tener la capacidad legal, autorización debida y/o las facultades necesarias y acreditadas para representar, efectuar la registración y para operar la Cuenta Virtual de la persona jurídica. La Empresa no será responsable por la falta de capacidad y/o facultades de las personas que operen la Cuenta Virtual de la persona jurídica siendo responsable esta última por todas las operaciones realizadas desde la misma. En ningún caso la persona jurídica podrá ampararse en la falta de facultades o autorizaciones para no cumplir con las obligaciones contraídas en la Plataforma.


4.2. Registración. Todo Usuario que desee utilizar los servicios ofrecidos en la Plataforma deberá registrarse en la Empresa y aceptar los Términos y Condiciones. Para la registración es obligatorio completar el formulario y acompañar toda la documentación de registración en todos sus campos con datos e información válidos. Todos los datos consignados por el Usuario al momento de registrarse se considerarán proporcionados bajo el carácter de Declaración Jurada siendo responsable por todos los daños y perjuicios derivados de la falsedad u omisión de la información enviada. La Empresa podrá verificar alguno o la totalidad de los datos aportados por los Usuarios recurriendo a diversas bases de datos y en su caso, podrá solicitar al Usuario que actualice, rectifique, complemente y/o aclare alguna situación vinculada a sus datos personales. En caso de existir dificultades para validar la información la Empresa podrá denegar la registración.


4.3. Cuenta Virtual. Al registrarse, el Usuario accederá a su Cuenta Virtual que le permitirá utilizar los servicios. Esta Cuenta Virtual se vinculará a la dirección de correo electrónico registrado y una clave de seguridad elegida por el Usuario. Esta última deberá adoptar las características de una clave segura. El Usuario se compromete a elegir una clave segura para su Cuenta Virtual y a mantener la confidencialidad de sus datos de ingreso y es el responsable exclusivo de ello. En virtud de lo expuesto, el Usuario será el único y exclusivo responsable por todas las operaciones efectuadas o registradas desde su Cuenta Virtual. La Empresa no será responsable por las operaciones concertadas como consecuencia de usos no autorizados o fraudulentos de la Cuenta Virtual del Usuario independientemente de que el titular/Usuario de la Plataforma haya informado sobre dicho uso no autorizado. La Cuenta Virtual de cada Usuario es personal, única e intransferible. La Empresa se reserva el derecho de rechazar a su exclusivo criterio cualquier solicitud de registración o de cancelar una registración previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento a favor del Usuario.


5. ¿Tiene costos operar con la Plataforma?
Según el tipo de Usuario y el servicio utilizado se deberán abonar los costos, gastos, impuestos, intereses y/o comisiones que se establezcan en cada caso y según el tipo de operación que lleve a cabo y/o el servicio utilizado (los “Costos”). Estos Costos podremos debitarlos y/o retenerlos de la Cuenta Bancaria o de la Cuenta Virtual o a través de cualquier otra forma de cobro disponible, para lo cual el Usuario autoriza expresamente a la Empresa y se obliga a no adoptar acciones que en forma alguna impidan u obstaculicen el cobro de dichos conceptos por parte de la misma. Ello es sin perjuicio de las demás acciones judiciales o extrajudiciales que le asistan a la Empresa. Los Costos por operar en la Plataforma serán los vigentes al día de cada operación y podrán ser modificadas a discreción de la Empresa. Cualquier modificación de Costos será debidamente informada a los Usuarios en forma previa.


Puedes consultar los Costos aquí


6. Cuenta Virtual asociada a CVU y Servicio de Billetera Digital.
6.1. Cuenta Virtual. El Usuario podrá acceder a una Cuenta Virtual, la que se encuentra integrada por los fondos acreditados y disponibles del Usuario. Cada Cuenta Virtual posee una Clave Virtual Uniforme (“CVU”) asociada, generada a requerimiento del mismo Usuario o proactivamente de manera automática por la Empresa.


6.2. Billetera digital. El Usuario brinda su consentimiento para enrolar y/o asociar las cuentas bancarias y/o de pago que usará en la billetera digital de la Empresa (la “Billetera Digital”).
Asimismo, el Usuario declara y reconoce que todas las cuentas bancarias y/o de pago enroladas y/o asociadas en la Billetera Digital de la Empresa son de su titularidad y provistas por una entidad financiera y/o proveedor de servicios de pago.
Toda instrucción de pago o de débito ordenada por el Usuario mediante la Billetera Digital se cursará mientras esté vigente el consentimiento o la autorización otorgada por el Usuario.
Oportunamente, el Usuario tendrá la posibilidad de establecer y modificar parámetros de uso de sus cuentas bancarias y/o de pago que haya vinculado en la Billetera Digital.
Por último, el Usuario podrá desvincular las cuentas bancarias y/o de pago enroladas a través de la Billetera Digital de la Empresa.


6.3. Ingreso y retiro de fondos. Transferencias. Los Usuarios pueden ingresar dinero en su Cuenta Virtual como resultado de (i) operaciones de cobro realizadas; (ii) operaciones de transferencias a las CVU de las Cuentas Virtuales; (iii) redes de cobranzas extrabancarias habilitadas y otros comercios habilitados; (iv) transferencias mediante débito inmediato ("DEBIN") desde cuentas bancarias de misma titularidad; y/o (v) transferencias mediante “Transferencias Inmediatas Pull” desde cuentas bancarias y/o cuentas de pago de misma titularidad.
Ingreso de dinero a través de DEBIN: A los fines de utilizar la modalidad de ingreso de dinero mediante DEBIN, el Usuario otorga un mandato a favor de la Empresa para que ésta genere por cuenta y orden del Usuario una autorización de carácter regular para débitos inmediatos de las cuentas bancarias de titularidad del Usuario registradas en la Plataforma.
Asimismo, para el caso de DEBIN, el Usuario podrá desconocer ante su entidad bancaria un débito realizado sobre su cuenta bancaria por los ingresos de dinero autorizados dentro del plazo de 30 (treinta) días, contados desde la fecha de la operación. Para ello, el Usuario deberá tener fondos en su Cuenta Virtual por un monto equivalente a la suma revertida. En caso de que el Usuario no contare con fondos suficientes para cubrir la reversa, el Usuario autoriza a la Empresa a debitar el monto correspondiente de los futuros ingresos de fondos a su Cuenta Virtual.
La Empresa podrá establecer límites a los ingresos de dinero realizados a través de redes de cobranzas extrabancarias habilitadas y otros comercios habilitados.
Una vez que los fondos estén acreditados y disponibles en su Cuenta Virtual, el Usuario podrá (i) mantener los fondos en su Cuenta Virtual para utilizarlos en otra oportunidad; o (ii) invertir los fondos en el fondo común de inversión; o (iii) retirar y/o utilizar los fondos, aplicando los mismos a: (a) el pago de los bienes o servicios mediante transacciones; (b) transferencias a otras cuentas bancarias o de pago propias o de terceros; (c) retiros en efectivo a través de redes de cobranzas extrabancarias habilitadas o comercios habilitados; (d) cualquier medio que la Empresa disponibilice a los Usuarios en el futuro.
El Usuario reconoce y acepta que las operaciones, la transferencia y/o retiro de los fondos quedará supeditado a la disponibilidad de fondos en la Cuenta Virtual del Usuario y al previo pago de cualquier deuda que el Usuario mantuviere con la Empresa, cualquiera fuera su causa.
Las transferencias serán ordenadas de manera inmediata, y para la realización de las transferencias se utilizarán los canales más eficientes que se encuentren disponibles para transferencias de fondos en el sistema nacional de pagos minorista. El Usuario reconoce y acepta que las transferencias ordenadas a través de la Plataforma se encuentran supeditadas al normal funcionamiento y cumplimiento de las autorizaciones de los participantes del sistema nacional de pagos involucrados. En caso de que ocurra un acontecimiento grave que pudiera afectar el sistema nacional de pagos, la disponibilidad inmediata de los fondos podría verse afectada, en cuyas las transferencias de fondos se cursarán en la primera oportunidad posible una vez superado dicho acontecimiento.
Por razones de seguridad, la Empresa podrá bloquear o retener las acreditaciones, transferencias, retiros y/o extracciones de fondos solicitados por aquellos Usuarios que en el último tiempo hayan recibido un porcentaje elevado de reclamos y/o se haya detectado y/o haya fuertes indicios o sospechas de que los mismos han utilizado los Servicios de la Empresa para realizar actividades fraudulentas, ilícitas y/o en contra de los Términos y Condiciones. Toda información sobre los fondos disponibles o retenidos, pendientes de liquidación en la Cuenta Virtual debe ser siempre verificada por el Usuario a través de la Plataforma.


7. Servicio de Procesamiento de Cobranzas y Pagos
7.1. Servicio de Procesamiento de Pagos. La Empresa brinda el servicio de procesamiento de cobro y pagos por cuenta y orden de sus Usuarios y de acuerdo con sus instrucciones (el “Servicio de Procesamiento de Pagos”), que puede involucrar distintos medios de pago, incluyendo tarjetas de débito, tarjetas de crédito, tarjetas prepagas, efectivo y dinero en la Cuenta virtual de los Usuarios (los “Medios de Pago”).
7.2. Mandato. Al utilizar los Servicios de Procesamiento de Pagos, el Usuario otorga un mandato a la Empresa para (i) pagar, por su cuenta y orden, una determinada suma de dinero; (ii) cobrar, por su cuenta y orden, una determinada suma de dinero. El mandato otorgado por el Usuario que hubiera efectuado la compra de un bien o servicio implica una autorización a favor de la Empresa para disponer en su nombre de ciertos fondos a través de los Medios de Pago y acreditarlos a favor de la persona que ofrezca y venda bienes y servicios. Asimismo, el mandato implica una autorización del Usuario a favor de la Empresa para recibir, cobrar y acreditar en su Cuenta Virtual los fondos correspondientes de acuerdo con sus instrucciones.
7.3. Celebración de la Solicitud de Procesamiento de Pagos. La Solicitud de Procesamiento de Pagos se celebrará mediante el envío por parte del Usuario de un formulario digital donde se detallarán las instrucciones respecto a los fondos. La Empresa se reserva el derecho de no procesar aquellas Solicitudes de Procesamiento de Pago que estén incompletas o en las cuales haya discrepancias entre los datos provistos, o cuando se identifiquen incumplimientos a los Términos y Condiciones, políticas de prevención de fraude.
7.4. Perfeccionamiento de la Solicitud. La Solicitud de Procesamiento de Pago no se considerará perfeccionada y la Empresa no asumirá responsabilidad u obligación alguna bajo la Solicitud de Procesamiento de Pago hasta tanto (i) la Empresa no haya aceptado la Solicitud de Procesamiento de Pago del Usuario, y (ii) el Usuario disponga de los fondos suficientes o se encuentre dentro de los límites de compra de conformidad con el Medio de Pago empleado.
Una vez aceptada y autorizada por la Empresa una Solicitud de Procesamiento de Pago del Usuario, la Empresa realizará el procesamiento del pago por cuenta y orden del Usuario, mediante la utilización de cualquiera de los Medios de Pago disponibles.
7.5. Liquidación y acreditación de los fondos. Los fondos se acreditarán en la Cuenta Virtual del Usuario conforme a las tarifas y plazos de liquidación informados, y de acuerdo con los mecanismos y reglas determinados por la Empresa y aceptados por el Usuario a través de estos Términos y Condiciones de Uso.
7.6. Reversiones, contracargos, desconocimiento de cargos efectuados por cualquier medio de pago. En el caso de que el Usuario haya recibido un pago y quien realizó el pago o el titular del medio de pago utilizado realizase una cancelación, anulación, contracargo, desconocimiento o reversión sobre los importes involucrados en la operación con posterioridad al pago, cualquiera sea el medio de pago utilizado para realizar la transacción, dichos importes serán descontados y debitados de la Cuenta Virtual del Usuario que vendió. En virtud de ello, el Usuario autoriza expresamente a la Empresa otorgándole un mandato suficiente e irrevocable, para debitar/retener de su Cuenta Virtual y/o de las cuentas que posea en cualquier entidad financiera de la República Argentina los fondos necesarios para cubrir dichos escenarios, y si no dispusiera de fondos suficientes, a debitarlos/retenerlos de cualquier otro ingreso futuro de fondos a su Cuenta Virtual y/o de las cuentas que posea en cualquier entidad financiera de la República Argentina.
El Usuario se obliga a conservar la documentación respaldatoria de la operación de venta del bien, producto, o prestación del servicio abonada mediante la Plataforma, inclusive aquella que compruebe el envío o entrega del bien o producto en cuestión y la prestación del servicio, por el plazo mínimo de un 1 año meses contado a partir de la recepción de los fondos correspondientes a la transacción.


8. ¿Dónde se encuentran los fondos de los Usuarios?
Los fondos de los Usuarios se encuentran en una o más Cuentas Recaudadoras, salvo que los Usuarios hayan retirado o utilizado los mismos o hayan instruido expresamente a la Empresa a invertir los saldos de su Cuenta Virtual en alguno de los Fondos Comunes de Inversión disponibles en la Plataforma. La Empresa no será responsable en ningún caso por las acciones, omisiones, medidas de seguridad ni la insolvencia del banco, entidad financiera o agente donde se encuentren las Cuentas Recaudadoras, la transferencia de los fondos o cualquier cambio legal o regulatorio que afecte a las Cuentas Recaudadoras. Es por ello que el Usuario acepta expresamente eximir de responsabilidad a la Empresa por acciones, insolvencia, incidentes de seguridad, ciberdelincuencia y cualquier otra situación que pudiera afectar a las entidades bancarias, financieras y/o agentes donde están depositados los fondos de las Cuentas Virtuales, como por situaciones políticas y económicas que pudieran presentarse en el país, y que sean ajenas a la Empresa. En estos casos, los Usuarios no podrán imputarle responsabilidad alguna a la Empresa, sus filiales o subsidiarias, empresas controlantes y/o controladas, ni exigir el reintegro del dinero o pago alguno.
En esas situaciones, la Empresa tendrá el derecho a optar por la opción que, a su solo criterio, sea la más conveniente pudiendo la Empresa optar incluso por aquella que considere más apropiada a fin de liquidar de manera rápida, sencilla y ordenada los fondos disponibles depositados en los bancos aun cuando implique reducciones, quitas o esperas en los montos depositados.


9. Intereses.
Los fondos disponibles o pendientes de liquidación en la Cuenta Virtual o en la Cuenta Recaudadora no generan intereses de ningún tipo a favor de los Usuarios. El Usuario podrá disponer en todo momento de los fondos disponibles para realizar las operaciones descritas en los Términos y Condiciones y/o sus Anexos una vez que resulten acreditados en su Cuenta conforme los plazos, mecanismos y reglas determinados por la Empresa.


10. Cumplimiento Normativo.
La Empresa está sujeta y debe cumplir con el Régimen de Información, Régimen de Retención y el Régimen de Retención sobre el Impuesto de Créditos y Débitos conforme las Resoluciones Generales de la Administración Federal de Ingresos Públicos (AFIP) que resulten aplicables y las modificatorias que en el futuro las remplacen.


11. Responsabilidad.
Responsabilidad del Usuario. Los Usuarios deberán respetar los Términos y Condiciones de la Empresa y la legislación aplicable.
La Empresa no será responsable ni garantizará el cumplimiento de las obligaciones que hubiesen asumido los Usuarios en relación a los pagos a efectuar o a recibir a través de la Plataforma y/o por las obligaciones asumidas por los mismos a través de las operaciones concertadas en la Plataforma. Tampoco la Empresa será responsable por los bienes, productos y servicios ofrecidos y comercializados por los Usuarios o terceros. El Usuario será el único y exclusivo responsable por tales obligaciones y operaciones.
Es obligación  de cada Usuario entregar en tiempo y forma los bienes y/o servicios ofrecidos, adquiridos y enajenados, conjuntamente con la documentación correspondiente vinculada a los mismos, y será el único y exclusivo responsable por la existencia, legitimidad y prestación de los bienes y servicios comercializados, calidad, cantidad, stock, disponibilidad, envíos, devoluciones, servicios de postventa y en general de cualquier otra circunstancia vinculada a los bienes y servicios que puedan ser ofrecidos y comercializados por cada Usuario y adquiridos por otro Usuario o tercero. Como Usuario reconoces y aceptas que, al realizar operaciones con otros Usuarios u otros terceros lo haces por tu propia voluntad, prestando tu consentimiento libremente, plenamente informado y bajo tu propio riesgo y responsabilidad.
El Usuario reconoce que será su responsabilidad los daños que se originen si a través de su Cuenta Virtual se imparten instrucciones de procesamientos de pagos fraudulentas, no autorizadas o erróneas.
En ningún caso, la Empresa será responsable por daño directo, emergente, moral, lucro cesante, o por cualquier otro daño y/o perjuicio, directo o indirecto, que haya podido sufrir el Usuario debido a las operaciones realizadas o no realizadas a través de la Plataforma.
En virtud de que la Empresa es ajena a la obligación que dio origen a los pagos entre los Usuarios, ésta no será responsable ni verificará las causas, importes o cualquier otra circunstancia relativa a dichas operaciones. El Usuario es el único y exclusivo responsable por ello. En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los involucrados en dichos reclamos o acciones eximen de toda responsabilidad a la Empresa y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados y se obligan a mantenerlos indemnes.
El Usuario es el único y exclusivo responsable por los datos ingresados y las personas autorizadas por él para operar con la Plataforma, siendo el único responsable ante la Empresa y terceros por ello. En ningún caso, la Empresa será responsable de los daños y perjuicios derivados de la inexactitud, omisión o falsedad de los datos consignados ni por el uso por parte de personas no autorizadas.
La Empresa no tiene vínculo ni relación alguna con las partes intervinientes de las respectivas operaciones, razón por la cual no tendrá responsabilidad alguna por las consecuencias dañosas derivadas de las relaciones entre dichas partes.
La Empresa aplica todas las medidas de seguridad que se encuentran a su alcance a los fines de dotar de seguridad y confianza a la Plataforma. Sin embargo, ninguna medida es inalienable, por ello la Empresa que no será responsable cuando el Usuario haya sido objeto de un acceso no autorizado o “hackeo” en su cuenta. Tampoco será responsable la Empresa por hechos, delitos, robos, fraudes, pagos, y/u operaciones realizadas a través de la Plataforma o valiéndose de la misma para ello, incluyendo, pero no limitando a hechos vinculados a robo, hurto, duplicación, falsificación de datos y/o cualquier otro fraude vinculado a las tarjetas de crédito, débito, cuentas bancarias o cualquier otro medio de pago de los cuales sean víctimas los Usuarios. En su mérito, los Usuarios liberan a la Empresa de toda responsabilidad por ello y renuncian a todo reclamo en su contra y/o a solicitar a la Empresa la restitución de los fondos afectados.
El acceso del Usuario a la Plataforma depende de servicios de terceros (tales como servicios de internet y de datos móviles). El Usuario acepta que la Empresa no tiene ninguna responsabilidad relacionada con el cumplimiento de servicios de terceros. En particular, el Usuario acepta que la conexión a Internet o a datos móviles necesaria para el funcionamiento del servicio es a su exclusivo cargo, por lo que asume tal responsabilidad y la Empresa no se responsabiliza por cualquier daño, perjuicio o pérdida al Usuario causados por fallas en el sistema, en el servidor o en Internet. Tampoco será responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audios contenidos en el mismo. Los Usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante o pérdida de chance en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet.
La Empresa no garantiza el acceso y uso continuado o ininterrumpido de su sitio y/o Plataforma. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a la Empresa. En tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad y liberando a la misma. La Empresa no será responsable por ningún error u omisión contenidos en la Plataforma. Sin perjuicio de lo expuesto, para el caso en que se pretenda atribuir o se atribuya responsabilidad legal a la Empresa frente al Usuario y/o cualquier tercero, será hasta el valor resultante del monto de la transacción involucrada.
La Empresa no garantiza el acceso ininterrumpido a las redes de cobranzas extrabancarias, comercios habilitados que ofrezcan la funcionalidad de retiro de efectivo, cajas de extracción o cajeros automáticos, los cuales pueden no estar disponibles debido a inconvenientes técnicos, fallas de internet, indisponibilidad o falta de recursos, o cualquier otro motivo ajeno a la Empresa.
Responsabilidad de la Empresa. Respecto de los Usuarios, en especial aquellos Usuarios alcanzados por las normas sobre “Protección de los usuarios de servicios financieros” del Banco Central de la República Argentina, la Empresa será responsable por cualquier incumplimiento a estos Términos y Condiciones, con el alcance previsto en las leyes y normativa vigente.


12. Indemnidad:
El Usuario mantendrá indemne a la Empresa (y/o a quienes brinden su licencia de Proveedor de Servicios de Pago (PSP) y licencien la tecnología para la prestación de los servicios objeto de estos Términos y Condiciones), y sus directores, gerentes, agentes, sucesores, administradores, representantes, apoderados, empleados, por cualquier reclamo, administrativo o judicial, iniciado por otros Usuarios o terceros o por cualquier organismo, relacionado con el uso de la Plataforma. Asimismo, el Usuario será responsable por el pago de cualquier multa, penalidad, daño y/o costo que sea aplicado a la Empresa (y/o a quienes brinden su licencia de Proveedor de Servicios de Pago (PSP) y licencien la tecnología para la prestación de los servicios objeto de estos Términos y Condiciones), como resultado de las transacciones realizadas por el Usuario en el marco de los Servicios. En virtud de lo previsto en esta cláusula, la Empresa y/o sus sociedades relacionadas podrán realizar compensaciones, retenciones u otras medidas necesarias para la reparación de pérdidas, daños y perjuicios, cualquiera sea su naturaleza.


13. Facultades y Sanciones.
La Empresa se reserva el derecho de investigar y, en caso de tomar conocimiento de incumplimientos a las obligaciones de Usuarios a los Términos y Condiciones y demás Anexos, así como a la normativa aplicable a la materia, la Empresa tendrá amplias facultades para advertir, suspender, restringir o inhabilitar temporal o definitivamente la Cuenta Virtual del Usuario y ejercer medidas de acción positiva tendientes a esclarecer la situación, solucionar los conflictos entre los Usuarios, cancelar operaciones y obtener el reintegro, reembolso o devolución del dinero abonado -en forma total- por cualquier medio, correspondiente a los bienes y servicios adquiridos por el Usuario, sin perjuicio de otras sanciones y/o medidas que se establezcan en los Anexos.


14. Embargos e Inhabilitación de Cuentas.
La Empresa en su carácter de Proveedor de Servicios de Pago, se encuentra facultado para trabar embargos y dar cumplimiento a cualquier medida cautelar ordenada por autoridad competente incluyendo sin limitación, la inhabilitación de la Cuenta Virtual del Usuario o embargos sobre los fondos disponibles o futuros de la misma.


15. Seguridad.
Por razones de seguridad, la Empresa podrá inhabilitar, suspender y/o cancelar temporal o definitivamente Cuentas Virtuales y/o Usuarios y/o bloquear las transferencias, movimientos, retiros y/o extracciones de fondos solicitados por aquellos Usuarios respecto de los cuales se haya detectado y/o haya fuertes indicios o sospechas de que los mismos han utilizado los servicios de la Plataforma o la Plataforma para realizar actividades fraudulentas, ilícitas y/o en contra de estos Términos y Condiciones o sus Anexos y/o sospechas de violación de preceptos legales por los cuales la Empresa deba responder.


16. Confidencialidad – Datos Personales.
En la Empresa nos preocupamos por mantener la confidencialidad de tus datos personales y proteger los mismos de accesos no autorizados. Es por ello que adoptamos todas las medidas de seguridad que se encuentran a nuestro alcance para velar por la protección de los mismos y evitar su divulgación y/o acceso no autorizado. Podrás conocer la forma en que protegemos, recabamos y tratamos tus datos personales accediendo a nuestras Políticas de Privacidad.


17. Servicios de Terceros.
A los fines de prestar nuestros servicios podremos utilizar o recurrir a servicios de terceros proveedores. En su mérito, toda autorización, mandato, renuncia, indemnidad, y en general, cualquier otra disposición prevista en estos Términos y Condiciones para la prestación de los servicios debe entenderse realizada por el Usuario a favor de la Empresa y/o sus proveedores de servicios.


18. Propiedad Intelectual.
Estos Términos y Condiciones, sus Anexos y demás políticas no implican ni implicarán total ni parcialmente la cesión ni la transmisión de derechos de propiedad intelectual, de autor ni de ningún tipo de derecho, patrimonial o no, vinculado y/o referido a la Plataforma. En su mérito, los Usuarios declaran y reconocen expresamente que todos los derechos de propiedad intelectual, de autor y de reproducción, así como cualquier derecho intelectual de cualquier naturaleza que sea, sobre la Plataforma y/o todo trabajo, estudio o desarrollo que se efectúe sobre la misma pertenecerán exclusivamente a su titular y/o licenciante y/o la persona física o jurídica a la que ésta decida cederlos. En razón de ello, los Usuarios renuncian de forma definitiva e irrevocable a invocar cualquier derecho de propiedad intelectual, de autor y/o de cualquier tipo sobre la Plataforma.


En el marco de las facultades concedidas, la Empresa autoriza al Usuario a hacer uso de la Plataforma, conforme los presentes Términos y Condiciones. Cualquier otro uso de la Plataforma queda estrictamente prohibido al Usuario.
Los Usuarios deben abstenerse de realizar cualquier acto u omisión que pueda causar daño o pérdida de reputación a la Empresa, o que pueda disminuir el valor de la marca, así como de utilizar cualquier propiedad intelectual de manera contraria a la ley, la moral y las buenas costumbres.


19. Partes Independientes.
Los Usuarios son considerados independientes, sin ninguna relación societaria o comercial fuera de la pactada en el presente acuerdo, y cada una de ellas mantendrá indemne a la otra por cualquier reclamo derivado de las obligaciones impositivas, laborales o previsionales y de cualquier naturaleza que estuvieran a su cargo. Ninguna de las Partes inducirá a error a persona alguna sobre su carácter de parte contractual independiente de la otra ni obligará a la otra parte frente a terceros. El incumplimiento de esta obligación por el Usuario habilitará a la Empresa a terminar el presente acuerdo de pleno derecho en cualquier momento.


20. Cesión.
El Usuario no podrá ceder, transferir, delegar o disponer de los derechos u obligaciones derivados del presente contrato, total o parcialmente. La Empresa podrá ceder, transferir, delegar o disponer de los derechos u obligaciones derivados del presente contrato, total o parcialmente, para lo cual el Usuario otorga su consentimiento.


21. Baja del Servicio. Terminación del Contrato.
La Empresa y el Usuario, por cualquiera de los canales habilitados y disponibles en la Plataforma o vía correo electrónico, podrán en cualquier oportunidad de vigencia del presente contrato terminarlo sin expresión de causa alguna, lo que implicará el cierre de la Cuenta Virtual del Usuario, pero no suspenderá el cumplimiento a todas las operaciones ya autorizadas y obligaciones pendientes de cumplimiento al momento de notificar la recisión. A los efectos de ejercer esta facultad, la Empresa notificará al Usuario con una antelación razonable de conformidad con la operatoria y actividad del Usuario. Asimismo, es necesario que la parte que pretende la terminación del contrato no adeude a la otra ni a terceros involucrados en las operaciones el cumplimiento de alguna obligación.
Asimismo, la Empresa podrá, en caso de incumplimiento del Usuario de estos Términos y Condiciones o de la legislación aplicable, dar por terminada la prestación de los Servicios, sin ningún tipo de aviso previo, reservándose el derecho de reclamar los daños y perjuicios que tal incumplimiento le haya causado.


22. Notificaciones.
Serán válidas y el Usuario acepta expresamente que todas las notificaciones realizadas a los Usuarios de la Empresa, incluyendo sin limitación a los avisos, recordatorios o comunicaciones relacionadas con los servicios brindados por la Empresa, sean dirigidas (i) a la dirección de correo electrónico principal registrada por éstos (domicilio especial electrónico) y/o (ii) a la Cuenta Virtual del Usuario.


23. Ley Aplicable y Jurisdicción.
Los presentes Términos y Condiciones se regirán en todos sus puntos por las leyes vigentes en la República Argentina. Cualquier controversia derivada del presente, su existencia, validez, interpretación, alcance o cumplimiento, será sometida para su resolución ante los Tribunales que resulten competentes conforme la legislación aplicable.


24. Domicilio.
Se fija domicilio de la Empresa en Obispo Oro 324, Córdoba, Argentina.


25. Anexos.
Forman parte integral e inseparable de los Términos y Condiciones, los siguientes documentos y/o secciones de la Empresa incorporados por referencia, donde se detallan Políticas de Privacidad y/o Términos y Condiciones de los diferentes servicios ofrecidos en la Plataforma. Los mismos se podrán consultar dentro de la Plataforma mediante el enlace abajo provisto o accediendo directamente a las páginas correspondientes:
`;
