name: Deploy Angular to S3 - Nonprod

on:
  push:
    branches:
      - nonprod

permissions:
  id-token: write
  contents: read
  issues: write

env:
  working_dir: "."
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "nonprod"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.13.0"

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ${{ env.working_dir }}

      - name: Build Angular app
        run: npm run build
        working-directory: ${{ env.working_dir }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./src/fe-treasury/dist/fe-treasury s3://905418314456-fe-treasury-bucket

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E1N61CT50LL6VC --paths "/*"
